project_id = "gtwgatewbagklpmxdlsj"

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = []

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_password_change = false
max_frequency = "1m0s"
otp_length = 8
otp_expiry = 3600