# Sync game-engine/.env from winway/.env.local (clone / main Supabase).
# Does not commit secrets — .env is gitignored in game-engine/.

$ErrorActionPreference = "Stop"
$root = Split-Path $PSScriptRoot -Parent
$localEnv = Join-Path $root ".env.local"
$engineEnv = Join-Path $root "game-engine\.env"

if (-not (Test-Path $localEnv)) {
  Write-Error "Missing $localEnv"
}

function Get-EnvValue($name) {
  $line = Get-Content $localEnv | Where-Object { $_ -match "^\s*$name=" } | Select-Object -First 1
  if (-not $line) { return $null }
  return ($line -replace "^\s*$name=", "").Trim()
}

$url = Get-EnvValue "NEXT_PUBLIC_SUPABASE_URL"
$key = Get-EnvValue "SUPABASE_SERVICE_ROLE_KEY"
$redisUrl = Get-EnvValue "UPSTASH_REDIS_REST_URL"
$redisToken = Get-EnvValue "UPSTASH_REDIS_REST_TOKEN"

if (-not $url -or -not $key) {
  Write-Error "NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY required in .env.local"
}

# Optional overrides: $env:GAME_RUNTIME / GAME_ENGINE_ROLES / GAME_ENGINE_API
$runtime = if ($env:GAME_RUNTIME) { $env:GAME_RUNTIME } else { "legacy_db" }
$roles = if ($env:GAME_ENGINE_ROLES) { $env:GAME_ENGINE_ROLES } else { "draw-processor" }
$api = if ($env:GAME_ENGINE_API) { $env:GAME_ENGINE_API } else { "false" }

$lines = @(
  "# Auto-generated by scripts/sync-game-engine-env.ps1 - do not commit",
  "SUPABASE_URL=$url",
  "SUPABASE_SERVICE_ROLE_KEY=$key",
  "",
  "GAME_ENGINE_ROLES=$roles",
  "GAME_RUNTIME=$runtime",
  "GAME_ENGINE_HTTP_PORT=8080",
  "GAME_ENGINE_API=$api",
  "LOG_LEVEL=info",
  "",
  "DRAW_PROCESSOR_INTERVAL_MS=500",
  "ROOM_SCHEDULER_INTERVAL_MS=1000",
  "TOURNAMENT_TICK_INTERVAL_MS=5000"
)

if ($redisUrl -and $redisToken) {
  $lines += ""
  $lines += "UPSTASH_REDIS_REST_URL=$redisUrl"
  $lines += "UPSTASH_REDIS_REST_TOKEN=$redisToken"
}

[System.IO.File]::WriteAllText($engineEnv, ($lines -join "`n") + "`n", [System.Text.UTF8Encoding]::new($false))
Write-Host "Wrote $engineEnv (runtime=$runtime roles=$roles api=$api)"
