# Writes .env.develop.local and game-engine/.env.develop.local from Supabase develop branch.
# Requires: supabase CLI logged in. Does not overwrite prod .env.local.

$ErrorActionPreference = "Stop"
$ParentRef = "ayybcrihxgtukwyeuoks"
$BranchName = "develop"
$Root = Split-Path -Parent $PSScriptRoot

Write-Host "Fetching Supabase branch '$BranchName'..."
$branch = supabase branches get $BranchName --project-ref $ParentRef -o json | ConvertFrom-Json

$nextEnv = @"
# Auto-generated by scripts/sync-supabase-develop-env.ps1 — Supabase develop branch
NEXT_PUBLIC_ADMIN_ORIGIN=http://localhost:3000
NEXT_PUBLIC_ACTIVE_GAMES_SOURCE=orchestrator
NEXT_PUBLIC_SUPABASE_URL=$($branch.SUPABASE_URL)
NEXT_PUBLIC_SUPABASE_ANON_KEY=$($branch.SUPABASE_ANON_KEY)
SUPABASE_SERVICE_ROLE_KEY=$($branch.SUPABASE_SERVICE_ROLE_KEY)
"@

$engineEnv = @"
# Auto-generated by scripts/sync-supabase-develop-env.ps1 — Supabase develop branch
SUPABASE_URL=$($branch.SUPABASE_URL)
SUPABASE_SERVICE_ROLE_KEY=$($branch.SUPABASE_SERVICE_ROLE_KEY)
GAME_ENGINE_ROLES=scheduler,draw-processor,tournament-orchestrator
GAME_RUNTIME=legacy_db
GAME_ENGINE_HTTP_PORT=8080
LOG_LEVEL=info
"@

$nextPath = Join-Path $Root ".env.develop.local"
$enginePath = Join-Path $Root "game-engine\.env.develop.local"

Set-Content -Path $nextPath -Value $nextEnv -Encoding utf8
Set-Content -Path $enginePath -Value $engineEnv -Encoding utf8

Write-Host "Wrote $nextPath"
Write-Host "Wrote $enginePath"
Write-Host ""
Write-Host "Next.js with develop DB: copy .env.develop.local -> .env.local (or use dotenv-cli)"
Write-Host "Game engine: cd game-engine; copy .env.develop.local .env"
